# whenever this is pushed to main, trigger this workflow
on:
  push:
    branches: [ 1-build ]

# these are things we're going to execute (the actual actions)
jobs:
  build:
    
    runs-on: ubunto-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: | 
          ./mvnw -B package --file pom.xml
          mkdir artifacts && cp target/*.jar artifacts
          
      - name: Persist Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JARtifact
          path: artifacts
